server:
  port: 10010

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        #路由id 可以自由发挥
        - id: user-service-route
          #uri: http://127.0.0.1:7777  #这里是uri != url
          uri: lb://user-service  #动态路由只需要指定服务名
          #http://localhost:10010/cloud/user/2
          #路由断言（匹配映射路径）
          predicates:
            #- Path=/cloud/user/** #所要匹配的路径 注意P大写
            #- Path=/**  #添加前缀
            - Path=/api/cloud/user/**
          filters: #路径过滤器
            #- PrefixPath=/cloud/user/  #添加前缀
            - StripPrefix=1  #去除前缀 /api/cloud/user/ => /cloud/user/ 去除第一个


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
