server:
  port: 10000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HsiangSun/spring_cloud_config.git
          username: HsiangSun
          password: who3429347113  #application.yml


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
