spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 1314
  application:
    name: user_service

server:
  port: 7777
  servlet:
    context-path: /cloud

mybatis:
  type-aliases-package: cn.hsiangsun.pojo
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
      #http://127.0.0.1:10086/eureka,http://127.0.0.1:10087/eureka,http://127.0.0.1:10088/eureka(同时将服务注册到多个注册中心)
  instance:
    prefer-ip-address: true #更倾向使用ip地址
    ip-address: 127.0.0.1

    #服务续约
    lease-renewal-interval-in-seconds: 30 #服务续约间隔 默认30秒 类似心跳
    lease-expiration-duration-in-seconds: 90  #服务失效时间 默认90秒


